# Generated by Django 5.0.6 on 2024-06-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='nome',
        ),
    ]
